name: Upload Nightly Binaries

on:
  schedule:
    - cron: '0 0 * * *' # run at midnight
  workflow_dispatch:

jobs:
  BuildAndUpload:
    uses: ./.github/workflows/test-build.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      ContainerRepositoryNameAndTag: "nightly-build:latest"
      BucketKey: "nightly-build/latest"
      PackageBucketKey: "nightly-build/latest"
